// Bilingual profile and research summaries, updated 8 October 2026.
// Research descriptions summarize areas of work, without proposal names or unpublished specifications.
const profileCopy = {
  en: {
    navPatents: "Patents",
    heroLead: "Postdoctoral researcher at The Chinese University of Hong Kong. My research connects robotic mechanism design with dynamics, control and autonomous manipulation.",
    aboutTitle: "Robotic mechanisms, models and control.",
    aboutP2: "My work covers cable-driven and parallel mechanisms, reconfigurable mobile robots, wearable assistance and soft manipulation. I study how geometry, stiffness, friction and contact affect robot performance, and develop models and control methods that I evaluate on physical prototypes.",
    aboutP3: "Recent research interests include task-adaptive robot bodies, human–robot collaboration, multimodal perception and flexible assembly. My experience spans mechanical design, fabrication, electronics, embedded control, simulation and experimental validation.",
    statSystems: "Granted utility models",
    researchTitle: "Research areas",
    research1Title: "Cable-driven & parallel mechanisms",
    research1Text: "Anthropomorphic manipulators and compact parallel mechanisms. Kinematic optimization, workspace analysis, geometric error modeling and stiffness regulation for precise, compliant motion.",
    research2Title: "Reconfigurable mobile robots",
    research2Text: "Wheel-leg and propeller-assisted robots that adapt their configuration for locomotion and manipulation. Body reorientation, contact stability and whole-body control in constrained environments.",
    research3Title: "Wearable robots & human augmentation",
    research3Text: "Lightweight wearable arms and relocatable bases for task-dependent reach. Human–robot coordination, active perception and shared-workspace planning for cooperative and parallel tasks.",
    research4Title: "Robot dynamics & adaptive control",
    research4Text: "Rigid–flexible dynamics, cable and joint friction, physically constrained parameter identification and sensorless force estimation. Adaptive feedforward compensation and compliant interaction control.",
    research5Title: "Soft robots & autonomous manipulation",
    research5Text: "Origami actuators, multimodal soft hands and deformable-object manipulation. Visual and tactile feedback, object-state estimation and motion prediction for grasping, catching and flexible assembly.",
    research6Title: "Precision & medical robotics",
    research6Text: "Compact mechanisms and integrated tools for confined-space operation. Hybrid positioning platforms, visual–force-guided microassembly and compliant tissue interaction.",
    patentLabel: "04 / PATENTS & SOFTWARE",
    patentTitle: "Patents & software",
    patentIntro: "My intellectual property covers anthropomorphic manipulators, spherical parallel transmissions, compliant mechanisms and climbing robots. The portfolio includes seven granted Chinese invention patents, ten granted utility models and one software copyright.",
    softwareTitle: "Registered software",
    softwareText: "Three-degree-of-freedom spatial parallel mechanism simulation software — 2018SR981520.",
    ipDirectionTitle: "Recent intellectual property work",
    ipDirectionText: "Additional patent work concerns reconfigurable multimodal and mobile manipulation robots, building on my mechanism and system development research.",
    granted: "Granted invention patent",
    experienceLabel: "05 / EXPERIENCE",
    footerText: "Open to conversations on robot mechanisms, control and autonomous manipulation.",
    pageDescription: "Yanlin Chen — robotics researcher working on cable-driven and parallel mechanisms, reconfigurable and wearable robots, dynamics, control and autonomous manipulation."
  },
  zh: {
    navPatents: "专利",
    heroLead: "香港中文大学博士后，研究机器人机构设计、动力学建模与控制，以及自主操作。",
    aboutTitle: "机器人机构、建模与控制。",
    aboutP2: "我的工作涵盖绳驱与并联机构、可重构移动机器人、穿戴式辅助机器人和软体操作。围绕几何构型、刚度、摩擦与接触对机器人性能的影响，建立模型、设计控制方法，并通过实物样机开展验证。",
    aboutP3: "近期关注任务自适应机器人本体、人机协作、多模态感知及柔性装配。研究经历覆盖机械设计、加工装配、电气与嵌入式控制、仿真分析和实验验证。",
    statSystems: "授权实用新型专利",
    researchTitle: "重点研究领域",
    research1Title: "绳驱机械臂与并联机构",
    research1Text: "研究仿人机械臂与紧凑并联机构的构型设计、运动学优化、工作空间评价、几何误差建模和刚度调节，兼顾运动精度与操作柔顺性。",
    research2Title: "可重构移动机器人",
    research2Text: "研究轮腿与旋翼辅助机器人的运动及操作构型，分析机体重定向、接触稳定性和全身协调控制，提升受限环境中的通行与作业能力。",
    research3Title: "穿戴式机器人与人机协作",
    research3Text: "研究轻量化机械臂和可移动附着基座，根据任务调整可达范围；结合人机协调、主动感知与共享空间规划，支持协同操作及并行任务。",
    research4Title: "机器人动力学辨识与控制",
    research4Text: "研究刚柔耦合动力学、绳索及关节摩擦、物理约束参数辨识和无力传感器的交互力估计，开展自适应前馈补偿与柔顺交互控制。",
    research5Title: "软体机器人与自主操作",
    research5Text: "研究折纸驱动器、多模态软手与柔性物体操作，融合视觉和触觉反馈、物体状态估计与运动预测，面向抓取、接物及柔性装配。",
    research6Title: "精密操作与医疗机器人",
    research6Text: "研究面向受限空间的紧凑机构与集成工具，结合混联定位平台、视觉力觉引导的微装配及柔顺组织交互，连接机构设计与场景操作需求。",
    patentLabel: "04 / 专利与软件",
    patentTitle: "专利与软件成果",
    patentIntro: "知识产权成果涵盖仿人机械臂、球面并联传动、柔顺机构与攀爬机器人，包括7项中国授权发明专利、10项授权实用新型专利和1项软件著作权。",
    softwareTitle: "软件著作权",
    softwareText: "三自由度空间并联机构仿真软件 — 2018SR981520。",
    ipDirectionTitle: "近期知识产权工作",
    ipDirectionText: "新增专利工作涉及可重构多模态机器人与移动操作机器人，延续机构设计和整机系统研发的研究积累。",
    granted: "授权发明专利",
    experienceLabel: "05 / 经历",
    footerText: "期待围绕机器人机构、控制与自主操作展开交流。",
    pageDescription: "陈彦霖，香港中文大学博士后。研究领域包括绳驱与并联机构、可重构移动和穿戴式机器人、动力学辨识与控制，以及自主操作。"
  }
};
