const publications = [
  [2026,"T-MECH","Stiffness Modeling and Experiments on a Low-Tension, Fully Actuated, Cable-Driven Manipulator with a Stiffness Regulator Module","Yanlin Chen, Yanjiang Huang, Qinlin Tan, et al.","IEEE/ASME Transactions on Mechatronics","https://doi.org/10.1109/TMECH.2026.3670275"],
  [2026,"NONLINEAR DYN.","Hybrid Offline–Online Identification and Adaptive Feedforward Compensation of Joint Friction for Robot Control","Yanjiang Huang, Z. Cai, C. Zhu, Yanlin Chen, et al.","Nonlinear Dynamics","https://doi.org/10.1007/s11071-026-12914-w"],
  [2026,"ADV. SCI.","Dual-Chamber One-Step Molding Actuator with Straight-Curved Crease Prismatic Design for Large-Range Motions and Structural Stability","Qinlin Tan, Yanlin Chen, Meng Zhou, et al.","Advanced Science","https://doi.org/10.1002/advs.202514441"],
  [2026,"RA-L","A VAGP-Based Adaptive Kalman Filter for Force Estimation of Robot","Yanjiang Huang, Xinyu Liu, Jianhong Ke, Yanlin Chen, et al.","IEEE Robotics and Automation Letters","https://scholar.google.com/scholar?q=A+VAGP-Based+Adaptive+Kalman+Filter+for+Force+Estimation+of+Robot"],
  [2026,"EAAI","Vision-Guided Robotic Sorting and Packing of Stacked Strawberries","Yanjiang Huang, J. Liu, Qinlin Tan, Yanlin Chen","Engineering Applications of Artificial Intelligence","https://scholar.google.com/scholar?q=Vision-Guided+Robotic+Sorting+and+Packing+of+Stacked+Strawberries"],
  [2026,"CASE","Pro-OMEGA2: Propeller-Assisted Robust 3D Hopping Robot with Hierarchical Force Allocation","Chuhan Zhang, Hongbo Zhang, Yanlin Chen, Xiangyu Chu, et al.","IEEE CASE 2026 · Best Paper Award nominee","https://scholar.google.com/scholar?q=Pro-OMEGA2+Propeller-Assisted+Robust+3D+Hopping+Robot"],
  [2025,"RA-L","OMEGA: Open-Source and Multi-Mode Hopping Platform for Educational and Groundwork Aims","Xiangyu Chu, Fei Yan Wong, Chun Yin Fan, Hongbo Zhang, Yanlin Chen, et al.","IEEE Robotics and Automation Letters, 10(4): 4005–4012","https://ieeexplore.ieee.org/document/10910197"],
  [2025,"JME","绳驱机器人动力学建模与控制研究综述","陈彦霖，邓小恒，张宪民，黄沿江","机械工程学报, 61(19): 1–17","https://scholar.google.com/scholar?q=绳驱机器人动力学建模与控制研究综述"],
  [2025,"CLAWAR","Appending Propellers to Leg for Enhancing Robustness of Hopping Locomotion","Yanlin Chen, Z. Chen, Yunxi Tang, K. W. Samuel Au, Xiangyu Chu","Climbing and Walking Robots Conference","https://scholar.google.com/scholar?q=Appending+Propellers+to+Leg+for+Enhancing+Robustness+of+Hopping+Locomotion"],
  [2024,"MMT","Error Modeling and Analysis of a Spherical Parallel Mechanism with a Multiloop Circuit Incremental Method","Yanlin Chen, Xianmin Zhang, Yanjiang Huang, et al.","Mechanism and Machine Theory, 191: 105525","https://scholar.google.com/scholar?q=Error+modeling+and+analysis+of+a+spherical+parallel+mechanism+multiloop+circuit"],
  [2023,"RAS","Kinematics Optimization of a Novel 7-DOF Redundant Manipulator","Yanlin Chen, Xianmin Zhang, Yanjiang Huang, et al.","Robotics and Autonomous Systems, 163: 104377","https://scholar.google.com/scholar?q=Kinematics+optimization+of+a+novel+7-DOF+redundant+manipulator"],
  [2022,"JMST","Novel Torsional Spring with Corrugated Flexible Units for Series Elastic Actuators for Cooperative Robots","Yanlin Chen, Yanjiang Huang, K. Chen, et al.","Journal of Mechanical Science and Technology, 36(6): 3131–3142","https://scholar.google.com/scholar?q=Novel+torsional+spring+with+corrugated+flexible+units"],
  [2020,"T-MECH","A Novel Cable-Driven 7-DOF Anthropomorphic Manipulator","Yanjiang Huang, Yanlin Chen, Xianmin Zhang, et al.","IEEE/ASME Transactions on Mechatronics, 26(4): 2174–2185","https://scholar.google.com/scholar?q=A+novel+cable-driven+7-DOF+anthropomorphic+manipulator"]
];
const reviews = [
  ["T-MECH","A Static Model of Cable-Driven Manipulators Considering Cable Bending Rigidity and Pulley Friction for Tension Feedback Estimation","D. Lin, Yanjiang Huang, Yanlin Chen, et al.","Major revision"],
  ["MMT","Global Identification of Robot Dynamic Parameters with LuGre Friction Model under a Dual-Excitation Alternating Iterative Identification Framework","Yanjiang Huang, Z. Cai, Yanlin Chen, et al.","Major revision"],
  ["NATURE COMM.","Force-Based Aerial Control for Extreme Maneuvers and Robust Landings in a Monopedal Robot","Xiangyu Chu, Chun Yin Fan, Yanlin Chen, et al.","Under review"],
  ["EAAI","Artificial Intelligence-Driven Six-Degree-of-Freedom Pose Forecasting for Autonomous Robotic Catching of Irregular Flying Objects","Yanjiang Huang, Z. Wang, Qinlin Tan, Yanlin Chen","Under review"],
  ["AIS","Mobile 3D Printing with Legged Robots for Ground Repair Using Computational Planning","Xiangyu Chu, Z. Zhang, Yanlin Chen, et al.","Under review"],
  ["T-MECH","Learning to Hop for a Single-Legged Robot with Parallel Mechanism","Hongbo Zhang, Yanlin Chen, Xiangyu Chu, et al.","Revision · arXiv:2501.11945"],
  ["ROBOTICA","Singularity and Interference Analysis and Workspace Optimization of a 3-RRR+S Spherical Parallel Mechanism","X. Deng, Yanlin Chen, Yanjiang Huang, Xianmin Zhang","Under review"]
];
let expanded=false;
function row(p,review=false){const [year,tag,title,authors,venue,href]=review?["In review",...p,"https://scholar.google.com/scholar?q="+encodeURIComponent(p[1])]:p;return `<a class="publication" href="${href}" target="_blank" rel="noreferrer"><div class="pub-year">${year}</div><div class="pub-tag">${tag}</div><div class="pub-main"><h3>${title}</h3><p>${authors}</p><span>${venue}</span></div><div class="pub-arrow">↗</div></a>`}
function render(){const asc=document.querySelector('#sortYear').value==='asc';const sorted=[...publications].sort((a,b)=>asc?a[0]-b[0]:b[0]-a[0]);document.querySelector('#publishedList').innerHTML=(expanded?sorted:sorted.slice(0,7)).map(p=>row(p)).join('');document.querySelector('#showMore').textContent=expanded?'Show fewer publications ↑':'Show all publications ↓'}
document.querySelector('#sortYear').addEventListener('change',render);document.querySelector('#showMore').addEventListener('click',()=>{expanded=!expanded;render()});document.querySelector('#reviewList').innerHTML=reviews.map(p=>row(p,true)).join('');document.querySelector('#reviewCount').textContent=reviews.length;document.querySelector('#themeToggle').addEventListener('click',()=>document.documentElement.classList.toggle('dark'));render();
