const publications = [
  [2026,"T-MECH","Stiffness Modeling and Experiments on a Low-Tension, Fully Actuated, Cable-Driven Manipulator with a Stiffness Regulator Module","Yanlin Chen, Yanjiang Huang, Qinlin Tan, et al.","IEEE/ASME Transactions on Mechatronics","https://doi.org/10.1109/TMECH.2026.3670275"],
  [2026,"NONLINEAR DYN.","Hybrid Offline–Online Identification and Adaptive Feedforward Compensation of Joint Friction for Robot Control","Yanjiang Huang, Z. Cai, C. Zhu, Yanlin Chen, et al.","Nonlinear Dynamics","https://doi.org/10.1007/s11071-026-12914-w"],
  [2026,"ADV. SCI.","Dual-Chamber One-Step Molding Actuator with Straight-Curved Crease Prismatic Design for Large-Range Motions and Structural Stability","Qinlin Tan, Yanlin Chen, Meng Zhou, et al.","Advanced Science","https://doi.org/10.1002/advs.202514441"],
  [2026,"RA-L","A VAGP-Based Adaptive Kalman Filter for Force Estimation of Robot","Yanjiang Huang, Xinyu Liu, Jianhong Ke, Yanlin Chen, et al.","IEEE Robotics and Automation Letters","https://scholar.google.com/scholar?q=A+VAGP-Based+Adaptive+Kalman+Filter+for+Force+Estimation+of+Robot"],
  [2026,"EAAI","Vision-Guided Robotic Sorting and Packing of Stacked Strawberries","Yanjiang Huang, J. Liu, Qinlin Tan, Yanlin Chen","Engineering Applications of Artificial Intelligence","https://scholar.google.com/scholar?q=Vision-Guided+Robotic+Sorting+and+Packing+of+Stacked+Strawberries"],
  [2026,"CASE","Pro-OMEGA2: Propeller-Assisted Robust 3D Hopping Robot with Hierarchical Force Allocation","Chuhan Zhang, Hongbo Zhang, Yanlin Chen, Xiangyu Chu, et al.","IEEE CASE 2026 · Best Paper Award nominee","https://scholar.google.com/scholar?q=Pro-OMEGA2+Propeller-Assisted+Robust+3D+Hopping+Robot"],
  [2025,"RA-L","OMEGA: Open-Source and Multi-Mode Hopping Platform for Educational and Groundwork Aims","Xiangyu Chu, Fei Yan Wong, Chun Yin Fan, Hongbo Zhang, Yanlin Chen, et al.","IEEE Robotics and Automation Letters, 10(4): 4005–4012","https://ieeexplore.ieee.org/document/10910197"],
  [2025,"JME","绳驱机器人动力学建模与控制研究综述","陈彦霖，邓小恒，张宪民，黄沿江","机械工程学报, 61(19): 1–17","https://scholar.google.com/scholar?q=绳驱机器人动力学建模与控制研究综述"],
  [2025,"CLAWAR","Appending Propellers to Leg for Enhancing Robustness of Hopping Locomotion","Yanlin Chen, Z. Chen, Yunxi Tang, K. W. Samuel Au, Xiangyu Chu","Climbing and Walking Robots Conference","https://scholar.google.com/scholar?q=Appending+Propellers+to+Leg+for+Enhancing+Robustness+of+Hopping+Locomotion"],
  [2024,"MMT","Error Modeling and Analysis of a Spherical Parallel Mechanism with a Multiloop Circuit Incremental Method","Yanlin Chen, Xianmin Zhang, Yanjiang Huang, et al.","Mechanism and Machine Theory, 191: 105525","https://scholar.google.com/scholar?q=Error+modeling+and+analysis+of+a+spherical+parallel+mechanism+multiloop+circuit"],
  [2023,"RAS","Kinematics Optimization of a Novel 7-DOF Redundant Manipulator","Yanlin Chen, Xianmin Zhang, Yanjiang Huang, et al.","Robotics and Autonomous Systems, 163: 104377","https://scholar.google.com/scholar?q=Kinematics+optimization+of+a+novel+7-DOF+redundant+manipulator"],
  [2022,"JMST","Novel Torsional Spring with Corrugated Flexible Units for Series Elastic Actuators for Cooperative Robots","Yanlin Chen, Yanjiang Huang, K. Chen, et al.","Journal of Mechanical Science and Technology, 36(6): 3131–3142","https://scholar.google.com/scholar?q=Novel+torsional+spring+with+corrugated+flexible+units"],
  [2020,"T-MECH","A Novel Cable-Driven 7-DOF Anthropomorphic Manipulator","Yanjiang Huang, Yanlin Chen, Xianmin Zhang, et al.","IEEE/ASME Transactions on Mechatronics, 26(4): 2174–2185","https://scholar.google.com/scholar?q=A+novel+cable-driven+7-DOF+anthropomorphic+manipulator"]
];
const reviews = [
  ["T-MECH","A Static Model of Cable-Driven Manipulators Considering Cable Bending Rigidity and Pulley Friction for Tension Feedback Estimation","D. Lin, Yanjiang Huang, Yanlin Chen, et al.","Major revision"],
  ["MMT","Global Identification of Robot Dynamic Parameters with LuGre Friction Model under a Dual-Excitation Alternating Iterative Identification Framework","Yanjiang Huang, Z. Cai, Yanlin Chen, et al.","Major revision"],
  ["NATURE COMM.","Force-Based Aerial Control for Extreme Maneuvers and Robust Landings in a Monopedal Robot","Xiangyu Chu, Chun Yin Fan, Yanlin Chen, et al.","Under review"],
  ["EAAI","Artificial Intelligence-Driven Six-Degree-of-Freedom Pose Forecasting for Autonomous Robotic Catching of Irregular Flying Objects","Yanjiang Huang, Z. Wang, Qinlin Tan, Yanlin Chen","Under review"],
  ["AIS","Mobile 3D Printing with Legged Robots for Ground Repair Using Computational Planning","Xiangyu Chu, Z. Zhang, Yanlin Chen, et al.","Under review"],
  ["T-MECH","Learning to Hop for a Single-Legged Robot with Parallel Mechanism","Hongbo Zhang, Yanlin Chen, Xiangyu Chu, et al.","Revision · arXiv:2501.11945"],
  ["ROBOTICA","Singularity and Interference Analysis and Workspace Optimization of a 3-RRR+S Spherical Parallel Mechanism","X. Deng, Yanlin Chen, Yanjiang Huang, Xianmin Zhang","Under review"]
];
const translations={
  en:{navAbout:"About",navResearch:"Research",navPublications:"Publications",navExperience:"Experience",heroLead:"Postdoctoral researcher at The Chinese University of Hong Kong, developing agile, precise and mechanically intelligent robotic systems.",contact:"Get in touch ↗",currentAt:"Currently at CUHK",aboutLabel:"01 / ABOUT",aboutTitle:"Mechanics and intelligence, designed as one system.",aboutP1:"I received my Ph.D. in Mechanical Engineering from South China University of Technology and am now a postdoctoral researcher at The Chinese University of Hong Kong and the Medical Robotics Innovation Technology Centre.",aboutP2:"My work spans cable-driven and anthropomorphic manipulators, multimodal hopping robots, parallel mechanisms, soft robots, medical robotics, system identification and intelligent control.",statPatents:"Granted invention patents",statSystems:"Robotic systems built",statRAndD:"Robotics R&D",researchLabel:"02 / RESEARCH",researchTitle:"From mechanism to machine",research1Title:"Multimodal hopping robots",research1Text:"Propeller-assisted hopping, flight, wheeled locomotion and mobile manipulation.",research2Title:"Cable-driven manipulators",research2Text:"Mechanism design, stiffness, error modeling, dynamics and control.",research3Title:"Medical and field robotics",research3Text:"Parallel mechanisms, integrated tools, soft robots and surgical systems.",research4Title:"Robot intelligence",research4Text:"Parameter identification, adaptive compensation, perception and autonomous operation.",publicationLabel:"03 / PUBLICATIONS",publicationTitle:"Research output",sortLabel:"Sort by year",newest:"Newest first",oldest:"Oldest first",reviewTitle:"Manuscripts under review",experienceLabel:"04 / EXPERIENCE",experienceTitle:"Experience & education",presentDate:"2024 — Present",postdoc:"Postdoctoral Researcher",postdocPlace:"The Chinese University of Hong Kong · Medical Robotics Innovation Technology Centre",phd:"Ph.D. in Mechanical Engineering",master:"M.Eng. in Mechanical Engineering",bachelor:"B.Eng. in Mechatronic Engineering",scut:"South China University of Technology",bachelorPlace:"South China University of Technology · GPA 3.73/4.0 · Rank 7/106",footerText:"Open to conversations on robotic mechanisms, systems and control."},
  zh:{navAbout:"简介",navResearch:"研究",navPublications:"论文",navExperience:"经历",heroLead:"香港中文大学博士后，致力于研发兼具敏捷运动、精密操作与机械智能的机器人系统。",contact:"联系我 ↗",currentAt:"现就职于香港中文大学",aboutLabel:"01 / 简介",aboutTitle:"让机械结构与智能控制共同定义机器人的能力。",aboutP1:"我于华南理工大学获得机械工程博士学位，目前在香港中文大学及医疗机器人创新技术中心从事博士后研究。",aboutP2:"研究涵盖绳驱与仿生机械臂、多模态跳跃机器人、并联机构、软体机器人、医疗机器人、系统辨识与智能控制。",statPatents:"授权发明专利",statSystems:"机器人系统研制",statRAndD:"持续机器人研发",researchLabel:"02 / 研究方向",researchTitle:"从机构到系统",research1Title:"多模态跳跃机器人",research1Text:"轮翼辅助跳跃、飞行、轮式运动与移动操作。",research2Title:"绳驱机械臂",research2Text:"机构设计、刚度、误差建模、动力学与控制。",research3Title:"医疗与地面作业机器人",research3Text:"并联机构、集成工具、软体机器人与手术机器人系统。",research4Title:"机器人智能",research4Text:"参数辨识、自适应补偿、环境感知与自主作业。",publicationLabel:"03 / 论文成果",publicationTitle:"研究成果",sortLabel:"按年份排序",newest:"最新优先",oldest:"最早优先",reviewTitle:"投稿中稿件",experienceLabel:"04 / 经历",experienceTitle:"工作与教育经历",presentDate:"2024 — 至今",postdoc:"博士后研究员",postdocPlace:"香港中文大学 · 医疗机器人创新技术中心",phd:"机械工程博士",master:"机械工程硕士",bachelor:"机械电子工程学士",scut:"华南理工大学",bachelorPlace:"华南理工大学 · GPA 3.73/4.0 · 排名 7/106",footerText:"期待围绕机器人机构、系统与控制展开交流。"}
};
let expanded=false,lang=localStorage.getItem('lang')||'en';
function row(p,review=false){const status=lang==='zh'?'投稿中':'In review';const [year,tag,title,authors,venue,href]=review?[status,...p,"https://scholar.google.com/scholar?q="+encodeURIComponent(p[1])]:p;return `<a class="publication" href="${href}" target="_blank" rel="noreferrer"><div class="pub-year">${year}</div><div class="pub-tag">${tag}</div><div class="pub-main"><h3>${title}</h3><p>${authors}</p><span>${venue}</span></div><div class="pub-arrow">↗</div></a>`}
function render(){const asc=document.querySelector('#sortYear').value==='asc';const sorted=[...publications].sort((a,b)=>asc?a[0]-b[0]:b[0]-a[0]);document.querySelector('#publishedList').innerHTML=(expanded?sorted:sorted.slice(0,7)).map(p=>row(p)).join('');document.querySelector('#reviewList').innerHTML=reviews.map(p=>row(p,true)).join('');document.querySelector('#showMore').textContent=expanded?(lang==='zh'?'收起 ↑':'Show fewer publications ↑'):(lang==='zh'?'显示全部论文 ↓':'Show all publications ↓')}
function applyLanguage(){document.documentElement.lang=lang==='zh'?'zh-CN':'en';document.querySelectorAll('[data-i18n]').forEach(el=>{const key=el.dataset.i18n;if(translations[lang][key])el.textContent=translations[lang][key]});document.querySelector('#langToggle').textContent=lang==='zh'?'EN':'中文';localStorage.setItem('lang',lang);render()}
document.querySelector('#sortYear').addEventListener('change',render);document.querySelector('#showMore').addEventListener('click',()=>{expanded=!expanded;render()});document.querySelector('#reviewCount').textContent=reviews.length;document.querySelector('#themeToggle').addEventListener('click',()=>document.documentElement.classList.toggle('dark'));document.querySelector('#langToggle').addEventListener('click',()=>{lang=lang==='en'?'zh':'en';applyLanguage()});applyLanguage();
